### ISSUE TITLE
Not working in angular v10

### ISSUE THREAD

**Issue by luwei6597** [fusioncharts/angular2-fusioncharts#104]
Warning: Entry point '@angular/core' contains deep imports into 'F:/Web/Angular/reporting.pkatalyst/node_modules/angular-fusioncharts/node_modules/rxjs/Observable', 'F:/Web/Angular/reporting.pkatalyst/node_modules/angular-fusioncharts/node_modules/rxjs/observable/merge', 'F:/Web/Angular/reporting.pkatalyst/node_modules/angular-fusioncharts/node_modules/rxjs/operator/share', 'F:/Web/Angular/reporting.pkatalyst/node_modules/angular-fusioncharts/node_modules/rxjs/Subject'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
Compiling @angular/core : es2015 as esm2015
Error: Error on worker #1: TypeError: Cannot read property 'fileName' of null
    at Object.getImportRewriter (F:\Web\Angular\reporting.pkatalyst\node_modules\@angular\compiler-cli\ngcc\src\rendering\utils.js:23:72)
    at DtsRenderer.renderDtsFile (F:\Web\Angular\reporting.pkatalyst\node_modules\@angular\compiler-cli\ngcc\src\rendering\dts_renderer.js:77:72)
    at F:\Web\Angular\reporting.pkatalyst\node_modules\@angular\compiler-cli\ngcc\src\rendering\dts_renderer.js:69:134
    at Map.forEach (<anonymous>)
    at DtsRenderer.renderProgram (F:\Web\Angular\reporting.pkatalyst\node_modules\@angular\compiler-cli\ngcc\src\rendering\dts_renderer.js:69:26)
    at Transformer.transform (F:\Web\Angular\reporting.pkatalyst\node_modules\@angular\compiler-cli\ngcc\src\packages\transformer.js:88:52)
    at F:\Web\Angular\reporting.pkatalyst\node_modules\@angular\compiler-cli\ngcc\src\execution\create_compile_function.js:52:42
    at F:\Web\Angular\reporting.pkatalyst\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\worker.js:85:54
    at step (F:\Web\Angular\reporting.pkatalyst\node_modules\@angular\compiler-cli\node_modules\tslib\tslib.js:143:27)
    at Object.next (F:\Web\Angular\reporting.pkatalyst\node_modules\@angular\compiler-cli\node_modules\tslib\tslib.js:124:57)
    at ClusterMaster.onWorkerMessage (F:\Web\Angular\reporting.pkatalyst\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:195:27)
    at F:\Web\Angular\reporting.pkatalyst\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:55:95
    at ClusterMaster.<anonymous> (F:\Web\Angular\reporting.pkatalyst\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:293:57)
    at step (F:\Web\Angular\reporting.pkatalyst\node_modules\@angular\compiler-cli\node_modules\tslib\tslib.js:143:27)
    at Object.next (F:\Web\Angular\reporting.pkatalyst\node_modules\@angular\compiler-cli\node_modules\tslib\tslib.js:124:57)
    at F:\Web\Angular\reporting.pkatalyst\node_modules\@angular\compiler-cli\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (F:\Web\Angular\reporting.pkatalyst\node_modules\@angular\compiler-cli\node_modules\tslib\tslib.js:113:16)
    at EventEmitter.<anonymous> (F:\Web\Angular\reporting.pkatalyst\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:287:32)
    at EventEmitter.emit (events.js:315:20)

**Comment by AyanBhadury** [comment]
Please try with angular-fusioncharts : 3.0.4

**Comment by Vishwas970** [comment]
> Please try with angular-fusioncharts : 3.0.4

Still not working :/

**Comment by mdarmousa** [comment]
I faced the same issue with Angular 11

**Comment by Ishangidwani** [comment]
any update on this ?

**Comment by AyanBhadury** [comment]
ngCC compilation issue has been fixed, please upgrade to 3.2.0 : http://www.npmjs.com/package/angular-fusioncharts

@Ishangidwani @luwei6597 @Vishwas970
